export const SIMULATION_PLAY = 'SIMULATION_PLAY';
export const SIMULATION_PAUSE = 'SIMULATION_PAUSE';
export const SIMULATION_GET_STATE = 'SIMULATION_GET_STATE';

export const HALL_GET_HALLS = 'HALL_GET_HALLS';
export const HALL_GET_HALL = 'HALL_GET_HALL';
export const HALL_GET_CURRENT_HALL = 'HALL_GET_CURRENT_HALL';
export const HALL_GET_TRUCK_AT_INDEX = 'HALL_GET_TRUCK_AT_INDEX';
export const HALL_CREATE = 'HALL_CREATE';
export const HALL_ADD_ASSEMBLY_LINE = 'HALL_ADD_ASSEMBLY_LINE';
export const HALL_REMOVE_ASSEMBLY_LINE = 'HALL_REMOVE_ASSEMBLY_LINE';
export const HALL_ADD_TRUCK = 'HALL_ADD_TRUCK';
export const HALL_UPDATE_TRUCK = 'HALL_UPDATE_TRUCK';
export const HALL_REMOVE_TRUCK = 'HALL_REMOVE_TRUCK';

export const WEATHER_GET_CITY = 'WEATHER_GET_CITY';
export const WEATHER_SET_CITY = 'WEATHER_SET_CITY';
export const WEATHER_GET_WEATHER = 'WEATHER_GET_WEATHER';
export const WEATHER_GET_LOCAL_WEATHER = 'WEATHER_GET_LOCAL_WEATHER';

export const SHAPE_CREATE_SHAPE = 'SHAPE_CREATE_SHAPE';
export const SHAPE_CREATE_RANDOM_SHAPE = 'SHAPE_CREATE_RANDOM_SHAPE';
